name: Build

on:
  # push:
  workflow_dispatch:
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    container: fpliu/ndk-pkg
    steps:
      - run: df -h
      - run: ndk-pkg env
      - run: ndk-pkg setup
      - run: ndk-pkg sysinfo
      - run: ndk-pkg update
      - run: ndk-pkg formula-repo-add
